#! /usr/bin/env zsh

bspc monitor DP-5 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width            2
bspc config focused_border_color    "#EC6798"
bspc config window_gap              12
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='I'
bspc rula -a Feishu desktop='III'
bspc rule -a Slack desktop='IV'
bspc rule -a zoom desktop='IV'
bspc rule -a Franz desktop='IV'
bspc rule -a WeChat desktop='IV' state=pseudo_tiled
bspc rule -a between.exe:Between desktop='IV' state=pseudo_tiled
bspc rule -a Spotify desktop='V'
bspc rule -a Termite desktop='VI'
bspc rule -a jetbrains-idea desktop='VII'
bspc rule -a jetbrains-clion desktop='VIII'
bspc rule -a Postman desktop='IX'
bspc rule -a Nemo desktop='X'
bspc rule -a Notion desktop='X'

# don't manage WeChat's emoticon context menu
bspc rule -a EmotionView manage=off

sxhkd &
dunst &
~/.config/polybar/launch.sh &
redshift -c ~/.config/redshift/redshift.conf &
feh --bg-fill ~/Pictures/tuscany_nights.jpg
picom &
xsetroot -cursor_name left_ptr
